//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 02:43:12 PM CEST 
//


package com.pgs.pandda.xml.task;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pgs.pandda.xml.task package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pgs.pandda.xml.task
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaskEditorTemplate }
     * 
     */
    public TaskEditorTemplate createTaskEditorTemplate() {
        return new TaskEditorTemplate();
    }

    /**
     * Create an instance of {@link TaskEditorTemplate.TaskInformation }
     * 
     */
    public TaskEditorTemplate.TaskInformation createTaskEditorTemplateTaskInformation() {
        return new TaskEditorTemplate.TaskInformation();
    }

    /**
     * Create an instance of {@link TaskEditorTemplate.Version }
     * 
     */
    public TaskEditorTemplate.Version createTaskEditorTemplateVersion() {
        return new TaskEditorTemplate.Version();
    }

    /**
     * Create an instance of {@link TaskEditorTemplate.ProjectName }
     * 
     */
    public TaskEditorTemplate.ProjectName createTaskEditorTemplateProjectName() {
        return new TaskEditorTemplate.ProjectName();
    }

    /**
     * Create an instance of {@link TaskEditorTemplate.TaskInformation.Parameter }
     * 
     */
    public TaskEditorTemplate.TaskInformation.Parameter createTaskEditorTemplateTaskInformationParameter() {
        return new TaskEditorTemplate.TaskInformation.Parameter();
    }

}
