//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.29 at 03:10:59 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.pgs.com/phase_tree_order", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.pgs.pandda.xml;
